### ISSUE TITLE
Can't find src files

### ISSUE THREAD

**Issue by hassanrehman01398** [muhammadfaraz6640/InstaGram-Clone-Mern-Stack#1]

**Comment by muhammadfaraz6640** [comment]
No Bro SRC files are not missing...Go to the master
branch-->clientside-->src...by default its showing empty main branch...

**Comment by muhammadfaraz6640** [comment]
https://github.com/muhammadfaraz6640/InstaGram-Clone-Mern-Stack/tree/master

this project is not completed.. i am currently working on it
